FROM openjdk:17
WORKDIR /seonghoon/chat
ARG JAR_FILE=build/libs/chat.jar
ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ARG AWS_REGION
ENV AWS_REGION=${AWS_REGION}
ARG SPRING_PROFILES_ACTIVE
ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
COPY ${JAR_FILE} chat.jar