apiVersion: v1
kind: Service
metadata:
  name: chat-core-service
  labels:
    service: chat-core
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    run: chat-core