apiVersion: v1
kind: Secret
metadata:
  name: secret-strimzi-cluster-operator
  annotations:
    kubernetes.io/service-account.name: strimzi-cluster-operator
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-cluster-operator
  namespace: kafka
